### ISSUE TITLE
Mocking framework

### ISSUE THREAD

**Issue by oleksiyp** [ygrenzinger/monopoly-kotlin#1]
Hi,

hope find you well with this cold call.

I am an author of [mocking framework for Kotlin](http://mockk.io)

I see you are using mockito-kotlin.

I just want you to be aware that there is solution that fully supports Kotlin and ask to try it in your new/current projects.

I can help you if you answer to this issue.

Thanks and please star [it](https://github.com/oleksiyp/mockk)

**Comment by ygrenzinger** [comment]
Thanks for the tip. I am looking at Kotlin but sadly it's not totally accepted by technical management at my current company so I don't know if I will be doing a real Kotlin project anytime soon.

**Comment by oleksiyp** [comment]
I have the same thing at work. Going to start writing tests in Kotlin at least to show how it can be useful.

Merry Xmas :christmas_tree:  :christmas_tree:  :christmas_tree:  :smiley:
